modLoader = "javafml"
loaderVersion = "[47,)"
issueTrackerURL="https://github.com/SamB440/huge-structure-blocks/issues"
license = "LGPL-3.0"

[[mods]]
modId = "hugestructureblocks"
version = "${version}"
displayName = "Huge Structure Blocks"
authors = "SamB440"
description = '''
Structure blocks. But bigger.
'''
#logoFile = ""

[[dependencies.hugestructureblocks]]
modId = "forge"
type = "required"
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"
mandatory = true

[[dependencies.hugestructureblocks]]
modId = "minecraft"
type = "required"
versionRange = "[1.20.1,1.20.2)"
ordering = "NONE"
side = "BOTH"
mandatory = true
