# Done to increase the memory available to Gradle.
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true

# Mod properties
mod_version = 1.1.9
maven_group = com.convallyria.hugestructureblocks
archives_name = huge-structure-blocks
enabled_platforms = fabric,neoforge

# Minecraft properties
minecraft_version = 26.1.2

# Dependencies
architectury_api_version = 19.0.1
fabric_loader_version = 0.19.2
fabric_api_version = 0.149.0+26.1.2
neoforge_version = 26.1.2.55-beta
